### ISSUE TITLE
Java 8 is not supported for jolokia-jvm-1.2.3-agent 

### ISSUE THREAD

**Issue by pavel-kolesnikov** [rhuss/jolokia#189]
Hi, 

I've got an error while launching the JVM agent with Java 8 tools.jar

```bash
$ java -cp $HOME/jdk-1.8-linux-64/lib/tools.jar:jolokia-jvm-1.2.3-agent.jar org.jolokia.jvmagent.client.AgentLauncher list
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/sun/tools/attach/VirtualMachine : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:191)
        at org.jolokia.jvmagent.client.util.ToolsClassFinder.lookupClass(ToolsClassFinder.java:52)
        at org.jolokia.jvmagent.client.util.VirtualMachineHandler.lookupVirtualMachineClass(VirtualMachineHandler.java:203)
        at org.jolokia.jvmagent.client.util.VirtualMachineHandler.listProcesses(VirtualMachineHandler.java:109)
        at org.jolokia.jvmagent.client.command.ListCommand.execute(ListCommand.java:44)
        at org.jolokia.jvmagent.client.command.CommandDispatcher.dispatchCommand(CommandDispatcher.java:77)
        at org.jolokia.jvmagent.client.AgentLauncher.main(AgentLauncher.java:62)
```

**Comment by rhuss** [comment]
What version of java are you using here ? I.e. could you please post the output of `java -version` ?

Thanks ...

**Comment by pavel-kolesnikov** [comment]
Ah, great! My default java version is "1.6.0_34". So I was trying to launch jolokia agent with 1.8 jar on java 1.6...
Sorry for disturbance. 

Now I launch with:```
$ $HOME/jdk-1.8-linux-64/bin/ja -cp $HOME/jdk-1.8-linux-64/lib/tools.jar:jolokia-jvm-1.2.3-agent.jar org.jolokia.jvmagent.client.AgentLauncher start 27453
Illegal Argument (command: start) : Cannot attach to process-ID 27453.
```
List of available processes lists only the agent. The process and agent are launched with
```
$ java -version
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)
```

Could you think of a possible cause of this?

PS Wow, such a prompt feedback!

**Comment by rhuss** [comment]
Of course, you can't attach to the agent process since after the list command the Java process stops (as is not valid anymore). Do you have other Java processes running on the Host ? What do you see when you use 'jps' (a tool, which comes with the JVM) ? 

BTW, you can't use a tools.jar from 1.8 with a 1.6 JVM since the byte format cannot be understood. Since tools.jar is very specific to its JVM, they should always fit.

Why don't you simply call `java -jar jolokia.jar list` as described in the documentation ?

**Comment by pavel-kolesnikov** [comment]
Sorry, I've been updating the comment...

**Comment by rhuss** [comment]
This can have multiple reasons. Do you know the JVM with which the process has been started ? Is it a Oracle one ? Or maybe a IBM JVM (like for Websphere) ?

Also very important: You have to start Jolokia with the very same user (UID) as the process to attach to. Being root is not enough.

**Comment by pavel-kolesnikov** [comment]
It is Oracle JVM. Indeed, I'm not the user who launched the java process I'm attaching to.

Ok. Launching the jolokia jvm agent with the same user who launched the application got me a success!

```
Started Jolokia for PID 27453
http://192.168.206.144:8778/jolokia/
```

Thank you so much!
