### ISSUE TITLE
Maximum number of threads used by Jolokia War Agent

### ISSUE THREAD

**Issue by arnabbiswas1** [rhuss/jolokia#235]
Hi Roland,

In our appliaction, we use Jolokia agent with Wildfly (Jolokia is just another war along with other wars/applications) and zabbix as monitoring server (Jolokia <--> zabbix). Recently we are hitting one issue (lab environment). Due to some networking problem, we obeserved that all the threads on Wildly are being consumed by Jolokia. Thread dump indicated that all the 100 Wildfly threads listening on 8778 (All the applications are listening on this port along with Jolokia) are being used by Jolokia trying to read the JSON object from the request sent by the other end. The threads remain in that state for hours (Zabbix continues to send JSON requests to Jolokia to read JMX data every 90 seconds). Since, there is no free thread on wildfly, any request to 8778 hangs (No response by the application).

```
"default task-95" #1056 prio=5 os_prio=0 tid=0x00007f4b6cd16800 nid=0x159c runnable [0x00007f4b3f0cc000]
   java.lang.Thread.State: RUNNABLE
  at sun.nio.ch.PollArrayWrapper.poll0(Native Method)
  at sun.nio.ch.PollArrayWrapper.poll(PollArrayWrapper.java:115)
  at sun.nio.ch.PollSelectorImpl.doSelect(PollSelectorImpl.java:73)
  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
  - locked <0x00000000f3803088> (a sun.nio.ch.Util$2)
  - locked <0x00000000f3803078> (a java.util.Collections$UnmodifiableSet)
  - locked <0x00000000f3801c18> (a sun.nio.ch.PollSelectorImpl)
  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
  at org.xnio.nio.SelectorUtils.await(SelectorUtils.java:46)
  at org.xnio.nio.NioSocketConduit.awaitReadable(NioSocketConduit.java:345)
  at org.xnio.conduits.AbstractSourceConduit.awaitReadable(AbstractSourceConduit.java:66)
  at io.undertow.conduits.ReadDataStreamSourceConduit.awaitReadable(ReadDataStreamSourceConduit.java:101)
  at io.undertow.conduits.FixedLengthStreamSourceConduit.awaitReadable(FixedLengthStreamSourceConduit.java:272)
  at org.xnio.conduits.AbstractSourceConduit.awaitReadable(AbstractSourceConduit.java:66)
  at io.undertow.server.handlers.HttpContinueReadHandler$ContinueConduit.awaitReadable(HttpContinueReadHandler.java:198)
  at org.xnio.conduits.AbstractSourceConduit.awaitReadable(AbstractSourceConduit.java:66)
  at io.undertow.server.handlers.HttpContinueReadHandler$ContinueConduit.awaitReadable(HttpContinueReadHandler.java:198)
  at org.xnio.conduits.ConduitStreamSourceChannel.awaitReadable(ConduitStreamSourceChannel.java:151)
  at io.undertow.channels.DetachableStreamSourceChannel.awaitReadable(DetachableStreamSourceChannel.java:77)
  at io.undertow.server.HttpServerExchange$ReadDispatchChannel.awaitReadable(HttpServerExchange.java:1951)
  at org.xnio.channels.Channels.readBlocking(Channels.java:295)
  at io.undertow.servlet.spec.ServletInputStreamImpl.readIntoBuffer(ServletInputStreamImpl.java:170)
  at io.undertow.servlet.spec.ServletInputStreamImpl.read(ServletInputStreamImpl.java:146)
  at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
  at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
  at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
  - locked <0x00000000f56b1e58> (a java.io.InputStreamReader)
  at java.io.InputStreamReader.read(InputStreamReader.java:184)
  at org.json.simple.parser.Yylex.zzRefill(Yylex.java:345)
  at org.json.simple.parser.Yylex.yylex(Yylex.java:541)
  at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
  at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
  at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
  at org.jolokia.http.HttpRequestHandler.extractJsonRequest(HttpRequestHandler.java:179)
  at org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:121)
  at org.jolokia.http.AgentServlet$3.handleRequest(AgentServlet.java:420)
  at org.jolokia.http.AgentServlet.handleSecurely(AgentServlet.java:313)
  at org.jolokia.http.AgentServlet.handle(AgentServlet.java:284)
  at org.jolokia.http.AgentServlet.doPost(AgentServlet.java:252)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
  at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
  at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
  at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
  at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
  at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
  at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
  at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
  at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
  at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261)
  at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:248)
  at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:77)
  at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:167)
  at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
  at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:761)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

```
Once the netwroking issue is addressed, things work properly. But, the concern is such a networking incident may happen at production as well where it makes more sense to compromise on monitoring than on real business application.

So, the question is :

Is there any way we can limit maximum number of concurrent requests handled by Jolokia War Agent?  That way we can "kind of" control the number of threads assigned for Jolokia by container. I see such an option for Jolokia JVM agent, but not for WAR agent. Do you feel any such rate limiting will make sense?

If you have any other suggestion, please let me know.

Thanks,
Arnab

**Comment by rhuss** [comment]
Since the Jolokia WAR agent acts as a regular servlet (like your other webapps) it can't influence how the thread model of the surroundig JEE server is configured (that's different to the JVM agent where the agent itself starts an HTTP Server and hence has full control over it). 

You probably can tune the configuration of your JEE server. E.g. for Tomcat you can setup a second connector with a different thread pool characteristic. See this [blog entry](https://labs.consol.de/de/jmx4perl/nagios/2010/08/18/putting-jmx4perl-on-the-fast-lane-for-tomcat.html) for an example. Something similar should be possible for JBoss with Undertow as well.

It is recommended anyway to separate the agent from the web applications, either by using the JVM agent or by using a dedicated channel for this. 

Hope this helps a bit, but since unfortunately Jolokia itself can't do much here, I'm closing this issue. Feel free to reopen it if you think the Jolokia servlet could do better (without taking over the tasks of the JEE server itself)

**Comment by arnabbiswas1** [comment]
Makes sense. For tomcat based application we are already using a different connector. I will try to figure it out for Wildfly or probably shift to JVM agent. 

I am just thinking aloud (It's not a suggestion). As an application, should not Jolokia have some rate limiting functionality? For example, if tomcat is configured for 1000 threads and under some scenario all the 1000 threads POST requests to Jolokia simultaneously, is it possible to have any performance impact?

**Comment by rhuss** [comment]
Of course if 1000 concurrent Jolokia requests arrive and Tomcat is configured for 1000 processing threads, there will be an impact in the same way when your application receives 1000 concurrent request for this Tomcat setup. 

However in your case its not 1000 concurrent but 1000 subsequent request which are hanging. I wonder whether JBoss could be configured for a timeout for request processing which would make much sense here and of course would solve your issue, too. tbh, I would have expected that there would be already a default timeout controlled by the server.

**Comment by arnabbiswas1** [comment]
Ideally yes. There should be some time out.

Thanks for your support!

**Comment by arnabbiswas1** [comment]
[Here] (http://deathbycode.blogspot.in/2015/12/wildfly-8x-control-maximum-number-of.html) are the steps to control maximum number of connections assigned to any application (Not specific to Jolokia) by Wildfly. I didn't find all the pieces together, so thought of capturing them.
