### ISSUE TITLE
InvocationTarget class com.sun.tools.attach.VirtualMachine (command: start) : null / Caused by: java.io.IOException: Connection refused

### ISSUE THREAD

**Issue by sameerparekh** [rhuss/jolokia#262]
I'm having trouble where my jolokia agent is unable to connect to my running Jenkins process. I ensured that it's running as same UID as the jenkins process itself. This is actually working fine on other hosts configured the same way.

any ideas?

```
[sbrenn@atla-anl-02-sr1 ~]$ /usr/lib/jvm/java-1.8.0-twitter/bin/java -jar /usr/local/bin/jolokia-jvm-agent.jar --version
Jolokia JVM Agent 1.2.0

[sbrenn@atla-anl-02-sr1 ~]$ sudo su - jenkins -c "/usr/lib/jvm/java-1.8.0-twitter/bin/java -jar /usr/local/bin/jolokia-jvm-agent.jar --port=30101 start $(cat /var/run/jenkins.pid) --verbose"
InvocationTarget class com.sun.tools.attach.VirtualMachine (command: start) : null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jolokia.jvmagent.client.util.VirtualMachineHandler.attachVirtualMachine(VirtualMachineHandler.java:66)
	at org.jolokia.jvmagent.client.AgentLauncher.main(AgentLauncher.java:57)
Caused by: java.io.IOException: Connection refused
	at sun.tools.attach.LinuxVirtualMachine.connect(Native Method)
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:124)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	... 6 more
```

**Comment by grgrzybek** [comment]
Please check with newer Jolokia version and newer JDK.
Are you sure about proper Linux permissions for running processes?

If you still think there's something to be fixed at Jolokia side, please reopen.
