### ISSUE TITLE
Jolokia wrongly detects Websphere MBeanServer

### ISSUE THREAD

**Issue by mohanaraosv** [rhuss/jolokia#296]
This problem already reported in the following link.  This problem still exist in the latest version.

http://jolokia.963608.n3.nabble.com/Jolokia-wrongly-detects-Websphere-MBeanServer-td4024280.html

Thanks,
Mohana.

**Comment by rhuss** [comment]
What error do you get exactly ? Could you paste a stackrtrace ? I ask because there _is_ a fix for the problem mentioned above, so that could be a new issue.

**Comment by mohanaraosv** [comment]
@rhuss  Please find the complete stack trace.

[WARNING] FAILED org.eclipse.jetty.server.Server@6380e9e9: java.lang.NoClassDefFoundError: com/ibm/websphere/management/MBeanFactory
java.lang.NoClassDefFoundError: com/ibm/websphere/management/MBeanFactory
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at org.jolokia.detector.WebsphereDetector.addMBeanServers(WebsphereDetector.java:83)
        at org.jolokia.backend.MBeanServers.<init>(MBeanServers.java:52)
        at org.jolokia.backend.MBeanServerExecutorLocal.init(MBeanServerExecutorLocal.java:84)
        at org.jolokia.backend.MBeanServerExecutorLocal.<init>(MBeanServerExecutorLocal.java:55)
        at org.jolokia.backend.MBeanServerHandler.<init>(MBeanServerHandler.java:75)
        at org.jolokia.backend.LocalRequestDispatcher.<init>(LocalRequestDispatcher.java:72)
        at org.jolokia.backend.BackendManager.init(BackendManager.java:330)
        at org.jolokia.backend.BackendManager.<init>(BackendManager.java:130)
        at org.jolokia.backend.BackendManager.<init>(BackendManager.java:105)
        at org.jolokia.http.AgentServlet.init(AgentServlet.java:140)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:640)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:419)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:875)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
        at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp(JettyWebAppContext.java:323)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
        at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:398)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:411)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:378)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:460)
        at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:328)
        at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:170)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: com.ibm.websphere.management.MBeanFactory
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:487)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)

**Comment by mohanaraosv** [comment]
@rhuss Do you agree is it a bug, if so i would like to fix it.

**Comment by rhuss** [comment]
@mohanaraosv Sorry for the delay.  I agree that the coding in the detector could be more defensive. Feel free to send a PR which does a more rigorous check for Websphere as it seems that detection mechanism in [detect()](https://github.com/rhuss/jolokia/blob/752c7423a08b5899448e3339746265727c94aabe/agent/core/src/main/java/org/jolokia/detector/WebsphereDetector.java#L52-L52) is not good enough. Note that it must be fixed in this method to not detect a Websphere server in your case (not sure actually what triggers the detection for you) . No idea where oglclient.jar contains or comes from, sorry.

**Comment by grgrzybek** [comment]
I can't download `ogclient-8.6.0.20150901-215917.jar` anywhere - google points me to "WebSphere eXtreme Scale client", but still I can't download it easily.

Looks like you need something more on the classpath besides this jar...

Please reopen if you think there's something to be fixed at Jolokia side.
