### ISSUE TITLE
Java 1.5 IBM (websphere 6.1) issue with wildcards

### ISSUE THREAD

**Issue by garnier-quentin** [rhuss/jolokia#312]
Hi,

Jolokia is deployed and it's ok. I try to use following syntax but it doesn't work:
```
java.lang:type=GarbageCollector,name=*
```

It's working well on tomcat, weblog...

The java version:
```
java version "1.5.0"
Java(TM) 2 Runtime Environment, Standard Edition (build pxa64dev-20060511 (SR2))
IBM J9 VM (build 2.3, J2RE 1.5.0 IBM J9 2.3 Linux amd64-64 j9vmxa6423-20060504 (JIT enabled)
J9VM - 20060501_06428_LHdSMr
JIT  - 20060428_1800_r8
GC   - 20060501_AA)
JCL  - 20060511a
```

The jolokia returns:
```
$VAR1 = bless( {
                 'request' => bless( {
                                       'attribute' => 'CollectionCount',
                                       'mbean' => 'java.lang:type=GarbageCollector,name=*',
                                       'path' => undef,
                                       'type' => 'read'
                                     }, 'JMX::Jmx4Perl::Request' ),
                 'stacktrace' => 'java.lang.IllegalArgumentException: Invalid object name. Invalid character \'*\' in value part of property
        at org.jolokia.request.JmxRequestFactory.createPostRequest(JmxRequestFactory.java:119)
        at org.jolokia.request.JmxRequestFactory.createPostRequests(JmxRequestFactory.java:137)
        at org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:123)
        at org.jolokia.http.AgentServlet$3.handleRequest(AgentServlet.java:420)
        at org.jolokia.http.AgentServlet.handleSecurely(AgentServlet.java:301)
        at org.jolokia.http.AgentServlet.handle(AgentServlet.java:277)
        at org.jolokia.http.AgentServlet.doPost(AgentServlet.java:244)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:763)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:856)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1146)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:592)
        at com.ibm.ws.wswebcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:525)
        at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:90)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:751)
        at com.ibm.ws.wswebcontainer.WebContainer.handleRequest(WebContainer.java:1478)
        at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:126)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:458)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewInformation(HttpInboundLink.java:387)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:267)
        at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
        at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
        at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:165)
        at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
        at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
        at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:136)
        at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:196)
        at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:751)
        at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:881)
        at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1497)
Caused by: javax.management.MalformedObjectNameException: Invalid character \'*\' in value part of property
        at javax.management.ObjectName.construct(ObjectName.java:544)
        at javax.management.ObjectName.<init>(ObjectName.java:1312)
        at org.jolokia.request.JmxObjectNameRequest.initObjectName(JmxObjectNameRequest.java:130)
        at org.jolokia.request.JmxObjectNameRequest.<init>(JmxObjectNameRequest.java:65)
        at org.jolokia.request.JmxReadRequest.<init>(JmxReadRequest.java:68)
        at org.jolokia.request.JmxReadRequest$1.create(JmxReadRequest.java:164)
        at org.jolokia.request.JmxReadRequest$1.create(JmxReadRequest.java:151)
        at org.jolokia.request.JmxRequestFactory.createPostRequest(JmxRequestFactory.java:117)
        ... 28 more
',
                 'status' => 400,
                 'error' => 'java.lang.IllegalArgumentException : Invalid object name. Invalid character \'*\' in value part of property',
                 'error_type' => 'java.lang.IllegalArgumentException'
               }, 'JMX::Jmx4Perl::Response' );
```

Thanks.

**Comment by rhuss** [comment]
Java 1.5 is really old, and it only supports JMX 1.0. So no wildcards are allowed as part of a property value. See http://docs.oracle.com/javase/1.5.0/docs/api/javax/management/ObjectName.html for details.

BTW you are somewhat lucky that Jolokia still runs on 1.5. The smallest version supported these days is 1.6 (which is EOL also already since end of 2012)

**Comment by rhuss** [comment]
@garnier-quentin You should be able to search for `java.lang:type=GarbageCollector,*` however.

**Comment by garnier-quentin** [comment]
Thanks for the quick response @rhuss !
