### ISSUE TITLE
Null Pointer Exception in Jolokia Agent Cleanup Thread

### ISSUE THREAD

**Issue by tlasica** [rhuss/jolokia#320]
With jolokia 1.3.5 loaded into Apache Cassandra jvm as an agent I hit once:
```
ERROR [Jolokia Agent Cleanup Thread] 2017-04-15 12:47:51,639  CassandraDaemon.java:207 - Exception in thread Thread[Jolokia Agent Cleanup Thread,5,main]
java.lang.NullPointerException: null
	at org.jolokia.jvmagent.CleanupThread.joinThreads(CleanupThread.java:101) ~[jolokia-jvm-agent.jar:na]
	at org.jolokia.jvmagent.CleanupThread.run(CleanupThread.java:60) ~[jolokia-jvm-agent.jar:na]
```
This is not repeatable, happened only once so far.

**Comment by apupier** [comment]
https://github.com/rhuss/jolokia/blob/a490b30923dbca1feb57da860ed316cc267d0eb4/agent/jvm/src/main/java/org/jolokia/jvmagent/CleanupThread.java#L101

**Comment by tlasica** [comment]
Thanks @apupier
