### ISSUE TITLE
Jolokia 1.6.2 not run in jetty 9.4

### ISSUE THREAD

**Issue by alvarolmedo** [rhuss/jolokia#406]
Tried with versions 9.4.9 and 9.4.18 of jetty.
The jolokia's version 1.6.2 return this WARN and the app is not available.
```
2019-06-24 11:04:20.857:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@4f933fd1{/jolokia,file:///tmp/jetty-0.0.0.0-8080-jolokia.war-_jolokia-any-8399330420656167226.dir/webapp/,UNAVAILABLE}{/jolokia.war}
java.lang.IllegalStateException: No LoginService for org.eclipse.jetty.security.authentication.BasicAuthenticator@3b07a0d6 in org.eclipse.jetty.security.ConstraintSecurityHandler@11a9e7c8
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.setConfiguration(LoginAuthenticator.java:76)
	at org.eclipse.jetty.security.SecurityHandler.doStart(SecurityHandler.java:354)
	at org.eclipse.jetty.security.ConstraintSecurityHandler.doStart(ConstraintSecurityHandler.java:448)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:123)
	at org.eclipse.jetty.server.session.SessionHandler.doStart(SessionHandler.java:503)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:123)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:844)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:505)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:447)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:579)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:240)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:419)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1588)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
```
The jolokia version 1.5.0 works fine in version 9.4.9 and 9.4.18, start correctly and reports version correctly:
```
{"request":{"type":"version"},"value":{"agent":"1.5.0","protocol":"7.2","config":{"listenForHttpService":"true","maxCollectionSize":"0","authIgnoreCerts":"false","agentId":"172.17.0.3-1-3c130745-servlet","agentType":"servlet","policyLocation":"classpath:\/jolokia-access.xml","agentContext":"\/jolokia","mimeType":"text\/plain","discoveryEnabled":"false","streaming":"true","historyMaxEntries":"10","allowDnsReverseLookup":"true","maxObjects":"0","debug":"false","serializeException":"false","detectorOptions":"{}","dispatcherClasses":"org.jolokia.jsr160.Jsr160RequestDispatcher","maxDepth":"15","authMode":"basic","canonicalNaming":"true","allowErrorDetails":"true","realm":"jolokia","includeStackTrace":"true","useRestrictorService":"false","debugMaxEntries":"100"},"info":{"product":"jetty","vendor":"Eclipse","version":"9.4.18.v20190429"}},"timestamp":1561374956,"status":200}
```

The log of jetty server startup:
```
2019-06-24 11:15:42.107:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@5b275dab{JSON JMX Agent,/jolokia,file:///tmp/jetty-0.0.0.0-8080-jolokia.war-_jolokia-any-1682148890222411936.dir/webapp/,AVAILABLE}{/jolokia.war}
2019-06-24 11:15:42.150:INFO:oejs.AbstractConnector:main: Started ServerConnector@279fedbd{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-06-24 11:15:42.151:INFO:oejs.Server:main: Started @1353ms
```

**Comment by alvarolmedo** [comment]
Same with jolokia 1.6.1

**Comment by alvarolmedo** [comment]
Solved with unsecure version.
```
2019-06-24 11:46:16.713:INFO:oejshC.jolokia:main: jolokia-agent: No access restrictor found, access to any MBean is allowed
2019-06-24 11:46:16.851:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@5b275dab{JSON JMX Agent,/jolokia,file:///tmp/jetty-0.0.0.0-8080-jolokia.war-_jolokia-any-3160568158246748162.dir/webapp/,AVAILABLE}{/jolokia.war}
2019-06-24 11:46:16.890:INFO:oejs.AbstractConnector:main: Started ServerConnector@710f4dc7{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-06-24 11:46:16.891:INFO:oejs.Server:main: Started @1193ms
```
