### ISSUE TITLE
can not gracefully stop jolokia

### ISSUE THREAD

**Issue by YiGene** [rhuss/jolokia#423]
i am excited find that we have such kind of tools to connect to a JVM and tried use it immediately. 
but i got issues after set it up 
i have a list of java process are running in the production box, since it didn't expose the jmx( and i can not change the scripts to enable jmx). so i tried to use jolokia to dynamically attach to the java process on the fly. i did a loop to attach ->get the jvm data->unattach, but after 4 process, it failed to start with error 
Couldn't start agent for PID 52258
Possible reason could be that port '8778' is already occupied.

while i try to stop it manually
it say 
Jolokia is not attached to PID 69277

run lsof it is actually still running with 69277 
/usr/sbin/lsof -i:8778
COMMAND   PID     USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
java    69277 test 853u  IPv4 179933620      0t0  TCP localhost:8778 (LISTEN)

do we know what caused this issue and how can we improve it

**Comment by YiGene** [comment]
"Jolokia Agent Cleanup Thread" daemon prio=10 tid=0xd5630800 nid=0x15e7 in Object.wait() [0xd67fe000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0xe395de98> (a java.lang.Thread)
        at java.lang.Thread.join(Thread.java:1186)
        - locked <0xe395de98> (a java.lang.Thread)
        at java.lang.Thread.join(Thread.java:1239)
        at org.jolokia.jvmagent.CleanupThread.joinThreads(CleanupThread.java:110)
        at org.jolokia.jvmagent.CleanupThread.run(CleanupThread.java:60)

"JolokiaDiscoveryListenerThread-10.193.60.46" daemon prio=10 tid=0xd562f800 nid=0x15e5 runnable [0xd6d5c000]
   java.lang.Thread.State: RUNNABLE
        at java.net.PlainDatagramSocketImpl.receive0(Native Method)
        - locked <0xee920878> (a java.net.PlainDatagramSocketImpl)
        at java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:145)
        - locked <0xee920878> (a java.net.PlainDatagramSocketImpl)
        at java.net.DatagramSocket.receive(DatagramSocket.java:725)
        - locked <0xee92c380> (a java.net.DatagramPacket)
        - locked <0xee920828> (a java.net.MulticastSocket)
        at org.jolokia.discovery.MulticastSocketListenerThread.receiveMessage(MulticastSocketListenerThread.java:115)
        at org.jolokia.discovery.MulticastSocketListenerThread.run(MulticastSocketListenerThread.java:72)

**Comment by YiGene** [comment]
and can confirm it is still connecting to that id 
curl -s http://127.0.0.1:8778/jolokia/read/java.lang:type=Runtime/Name
{"timestamp":1572251252,"status":200,"request":{"mbean":"java.lang:type=Runtime","attribute":"Name","type":"read"},"value":"69277@myserver"}
