### ISSUE TITLE
Jolokia agent fails on Elastic Search 6

### ISSUE THREAD

**Issue by fbacchella** [rhuss/jolokia#449]
I tried to run jolokia as an agent in ElasticSearch 6 with the following command:

    ../bin/java ... -javaagent:/data/elasticsearch/lib/jolokia-jvm-agent.jar=config=/data/elasticsearch/conf/jolokia.properties -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /data/elasticsearch/run/elasticsearch.pid --quiet

And the config file is:

    host: 0.0.0.0
    port: 8997
    protocol: http
    discoveryEnabled: false
    debug: true

But it fails:
```
curl -v http://XXXX:8997/jolokia/
*   Trying XXXXX...
* TCP_NODELAY set
* Connected to XXXXXX port 8997 (#0)
> GET /jolokia/ HTTP/1.1
> Host: 10.83.5.21:8997
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

And nothing is logged, on stdout, I only got:
```
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL https://XXX:8997/jolokia/
```

If I check the threads:

```
jstack 5160 |  grep -i jolokia
"Jolokia Agent Cleanup Thread" #18 daemon prio=5 os_prio=0 cpu=0.94ms elapsed=10200.51s tid=0x00007f48b8063800 nid=0x148f in Object.wait()  [0x00007f48bf8f0000]
	at org.jolokia.jvmagent.CleanupThread.joinThreads(CleanupThread.java:110)
	at org.jolokia.jvmagent.CleanupThread.run(CleanupThread.java:60)
```

So there is only one jolokia thread. I'm not sure that OK.

Any hint ?

**Comment by grgrzybek** [comment]
@fbacchella is this still a problem for you?

**Comment by fbacchella** [comment]
Give me a little time to retry.

**Comment by fbacchella** [comment]
I downloaded and installed jolokia-agent-jvm-2.1.0-javaagent.jar:

```
sudo cksum /data/elasticsearch/lib/jolokia-jvm-agent.jar jolokia-agent-jvm-2.1.0-javaagent.jar 
1310362372 636179 /data/elasticsearch/lib/jolokia-jvm-agent.jar
1310362372 636179 jolokia-agent-jvm-2.1.0-javaagent.jar
```

Started ES with:

```
-javaagent:/data/elasticsearch/lib/jolokia-jvm-agent.jar=config=/data/elasticsearch/conf/jolokia.properties
```


With `logHandlerClass: org.jolokia.server.core.service.impl.Stdout` in jolokia.properies, I got:

```
Could not start Jolokia agent: java.lang.NullPointerException: Cannot invoke "org.jolokia.server.core.service.api.LogHandler.info(String)" because "log" is null
```

Without:
```
Jolokia: Agent started with URL http://127.0.0.1:8998/jolokia/
```

But it still fails:

```
curl -v http://127.0.0.1:8998/jolokia/
*   Trying 127.0.0.1:8998...
* Connected to 127.0.0.1 (127.0.0.1) port 8998 (#0)
> GET /jolokia/ HTTP/1.1
> Host: 127.0.0.1:8998
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

I checked with status:

```
sudo .../java-openjdk-21_latest/bin/java  -jar jolokia-agent-jvm-2.1.0-javaagent.jar status 79901
Jolokia started for PID 79901
http://127.0.0.1:8998/jolokia/
```

The `jolokia.properties`:
```
port: 8998
protocol: http
discoveryEnabled: false
debug: true
executor: fixed
threadNr: 5
```

**Comment by grgrzybek** [comment]
Thanks for quick feedback about old issue! I'll have a look.

**Comment by grgrzybek** [comment]
@fbacchella I'm not an ES expert, so while I have your attention, may I ask for quick help about how to start Elastic Search as you did? (version, initial setup, ...)

**Comment by grgrzybek** [comment]
Mind that the class should be `org.jolokia.server.core.service.impl.StdoutLogHandler`.

**Comment by grgrzybek** [comment]
asciidoc/wrapping issue...

**Comment by fbacchella** [comment]
It works better with `org.jolokia.server.core.service.impl.StdoutLogHandler`, but it’s not really verbose. Still failing silently.

**Comment by fbacchella** [comment]
One possible source of problem is that ES insist on using a security manager even if it’s deprecated and scheduled to be removed. I was unable to setup it in a “transparent” mode that will allow everything. But I was expecting at least a complain from Jolokia about a security violation.

**Comment by grgrzybek** [comment]
With simple check I couldn't start Jolokia agent within Elasticsearch:
```
WARNING: A Java agent has been loaded dynamically (/data/tmp/elasticsearch-8.15.1/lib/jolokia-agent-jvm-2.1.1-SNAPSHOT-javaagent.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.instrument@22.0.1/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
	at java.instrument@22.0.1/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:582)
Caused by: java.lang.NoClassDefFoundError: com/sun/net/httpserver/Authenticator
	at jolokia.agent.jvm@2.1.1-SNAPSHOT-javaagent/org.jolokia.jvmagent.JvmAgent.agentmain(JvmAgent.java:85)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.sun.net.httpserver.Authenticator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 5 more
```

**Comment by grgrzybek** [comment]
Works with these options in `/data/tmp/elasticsearch-8.15.1/config/jvm.options`:
```
--add-modules=jdk.httpserver
-javaagent:/data/tmp/elasticsearch-8.15.1/lib/jolokia-agent-jvm-2.1.1-SNAPSHOT-javaagent.jar=config=/data/tmp/elasticsearch-8.15.1/config/jolokia.properties
```

**Comment by fbacchella** [comment]
Damn JPMS !

**Comment by grgrzybek** [comment]
You're right about security manager (which btw is going to be removed). I debugged ES + Jolokia and saw the exception, which then I tracked in the logs:
```
[2024-09-10T10:07:07,133][WARN ][stderr                   ] [everfree.forest] Could not start Jolokia agent: java.security.AccessControlException: access denied ("java.net.SocketPermission" "localhost:8998" "listen,resolve")
```

**Comment by grgrzybek** [comment]
Hmm, I saw some other easy-to-fix SecurityManager issues - I had to add:
```
    permission java.net.SocketPermission "*:8998", "accept,connect,listen,resolve";
    permission java.lang.RuntimePermission "getClassLoader";
    permission java.util.PropertyPermission "*", "read,write";
    permission java.lang.RuntimePermission "shutdownHooks";
```

to `/data/tmp/elasticsearch-8.15.1/jdk/conf/security/java.policy` and under debugger I saw proper initialization of Jolokia-owned `sun.net.httpserver.ServerImpl$Dispatcher` and I see the thread:
```
"HTTP-Dispatcher@27734" tid=0x67 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:454)
	  at java.lang.Thread.runWith(Thread.java:1583)
	  at java.lang.Thread.run(Thread.java:1570)
```

But I still can't connect.

**Comment by grgrzybek** [comment]
Under wireshark I see `RST`:
```
No.	Time	Source	Destination	Protocol	Length	Port from	Port to	Info
114	1.632449644	127.0.0.1	127.0.0.1	TCP	74	60810	8998	60810 → 8998 [SYN] Seq=0 Win=65495 Len=0 MSS=65495 SACK_PERM TSval=1860109463 TSecr=0 WS=128
115	1.632466169	127.0.0.1	127.0.0.1	TCP	74	8998	60810	8998 → 60810 [SYN, ACK] Seq=0 Ack=1 Win=65483 Len=0 MSS=65495 SACK_PERM TSval=1860109463 TSecr=1860109463 WS=128
116	1.632478044	127.0.0.1	127.0.0.1	TCP	66	60810	8998	60810 → 8998 [ACK] Seq=1 Ack=1 Win=65536 Len=0 TSval=1860109463 TSecr=1860109463
117	1.632519396	127.0.0.1	127.0.0.1	HTTP	158	60810	8998	GET /jolokia/version HTTP/1.1 
118	1.632525988	127.0.0.1	127.0.0.1	TCP	66	8998	60810	8998 → 60810 [ACK] Seq=1 Ack=93 Win=65408 Len=0 TSval=1860109463 TSecr=1860109463
119	1.633037561	127.0.0.1	127.0.0.1	TCP	66	8998	60810	8998 → 60810 [RST, ACK] Seq=1 Ack=93 Win=65536 Len=0 TSval=1860109464 TSecr=1860109463
```

**Comment by grgrzybek** [comment]
Oh yeah. I caught SecurityException and got `("java.net.SocketPermission" "127.0.0.1:33536" "accept,resolve")` this in:
```
"HTTP-Dispatcher@27734" tid=0x67 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.security.AccessControlContext.checkPermission(AccessControlContext.java:488)
	  at java.security.AccessController.checkPermission(AccessController.java:1085)
	  at java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
	  at java.lang.SecurityManager.checkAccept(SecurityManager.java:1021)
	  at sun.nio.ch.ServerSocketChannelImpl.finishAccept(ServerSocketChannelImpl.java:504)
	  at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:415)
	  at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:489)
	  at java.lang.Thread.runWith(Thread.java:1583)
	  at java.lang.Thread.run(Thread.java:1570)
```

**Comment by fbacchella** [comment]
It looks like the real good solution to have Jolokia works from inside Elastic would be to write a specific plugin for it. Plugins are allowed to handle some URL like _jolokia, and provides specific permissions. But I never wrote a plugin for Elastic.

**Comment by grgrzybek** [comment]
Hmm, ES seems to read different policy file: https://github.com/elastic/elasticsearch/blob/main/server/src/main/resources/org/elasticsearch/bootstrap/security.policy

**Comment by grgrzybek** [comment]
Another file read is `file:/data/tmp/elasticsearch-8.15.1/modules/x-pack-watcher/plugin-security.policy`

**Comment by fbacchella** [comment]
On my setup:

```
$ find /usr/share/elasticsearch -name '*.policy'
/usr/share/elasticsearch/jdk/conf/security/java.policy
/usr/share/elasticsearch/jdk/conf/security/policy/limited/default_US_export.policy
/usr/share/elasticsearch/jdk/conf/security/policy/limited/default_local.policy
/usr/share/elasticsearch/jdk/conf/security/policy/limited/exempt_local.policy
/usr/share/elasticsearch/jdk/conf/security/policy/unlimited/default_US_export.policy
/usr/share/elasticsearch/jdk/conf/security/policy/unlimited/default_local.policy
/usr/share/elasticsearch/jdk/lib/security/default.policy
/usr/share/elasticsearch/modules/ingest-geoip/plugin-security.policy
/usr/share/elasticsearch/modules/lang-expression/plugin-security.policy
/usr/share/elasticsearch/modules/lang-mustache/plugin-security.policy
/usr/share/elasticsearch/modules/lang-painless/plugin-security.policy
/usr/share/elasticsearch/modules/reindex/plugin-security.policy
/usr/share/elasticsearch/modules/repository-encrypted/plugin-security.policy
/usr/share/elasticsearch/modules/repository-url/plugin-security.policy
/usr/share/elasticsearch/modules/searchable-snapshots/plugin-security.policy
/usr/share/elasticsearch/modules/systemd/plugin-security.policy
/usr/share/elasticsearch/modules/transport-netty4/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-analytics/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-async/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-async-search/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-ccr/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-core/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-deprecation/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-eql/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-graph/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-identity-provider/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-logstash/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-ml/plugin-security-test.policy
/usr/share/elasticsearch/modules/x-pack-ml/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-monitoring/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-security/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-sql/plugin-security.policy
/usr/share/elasticsearch/modules/x-pack-watcher/plugin-security.policy
/usr/share/elasticsearch/plugins/search-guard-flx/plugin-security.policy
```

**Comment by grgrzybek** [comment]
I have to give up (I'm not an expert on ES)... Or at least stop digging for now.

despite adding the permissions to ES' own JDK (`jdk/conf/security/java.policy`) I'm still getting e.g., `java.security.AccessControlException: access denied ("java.net.SocketPermission" "127.0.0.1:45668" "accept,resolve")` in:
```
"HTTP-Dispatcher@5429" tid=0x2c nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.ServerSocketChannelImpl.finishAccept(ServerSocketChannelImpl.java:510)
	  at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:415)
	  at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:489)
	  at java.lang.Thread.runWith(Thread.java:1583)
	  at java.lang.Thread.run(Thread.java:1570)
```

If not the security manager, the request would be handled by Jolokia, but I'm not sure (and I can't quickly google for Java Security Manager policy config for ES) how to declare required properties...

**Comment by grgrzybek** [comment]
I even added:
```
grant codeBase "file:/data/tmp/elasticsearch-8.15.1/lib/jolokia-agent-jvm-2.1.1-SNAPSHOT-javaagent.jar" {
    permission java.net.SocketPermission "*:8998", "accept,connect,listen,resolve";
    permission java.lang.RuntimePermission "getClassLoader";
    permission java.util.PropertyPermission "*", "read,write";
    permission java.lang.RuntimePermission "shutdownHooks";
    permission java.net.SocketPermission "127.0.0.1:*" "accept,resolve";
};
```

to `/data/tmp/elasticsearch-8.15.1/jdk/conf/security/java.policy` and still nothing.

**Comment by grgrzybek** [comment]
Thanks for great cooperation - in theory we just have to find proper `java.policy` file and add required permissions. I just couldn't find this file and couldn't find anything in ES docs.

**Comment by fbacchella** [comment]
If someone with more time that both of US found this issue, a good start point should be https://github.com/elastic/elasticsearch/tree/main/plugins/examples/rest-handler.
